### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [christophM/interpretable-ml-book#125]
Thanks for writing & publishing this book!

Looks like this book is licensed under [CC-BY-NC-SA 4.0][license], so it would be helpful to have a `LICENSE` file in the repo with the content of [full text of this license][license-text] to make it clear, and GitHub will also annotate the repo accordingly.

[license]: https://github.com/christophM/interpretable-ml-book/blob/cfcf3ecc897593554c33d6b54b99e25b7c57e400/manuscript/00.0-preface.Rmd#L47-L49
[license-text]: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt

**Comment by christophM** [comment]
I didn't do that yet since I am not sure what license to apply. 

While the book is licensed under CC-BY-NC-SA 4.0, the repository is another thing, because it is the software that builds the book (but also holds the contents of the book). Creative Commons licenses are not suitable for software.  If use a software license like the MIT license for the repository, would that have any implications on what people are allowed to do with the book?

I would like to allow the following use case: Someone clones the repository, deletes the book's contents writes their own book using the same software and sells that book.

I want to forbid following case: Someone clones the repository, builds the interpretable ml book and sells it.

Any ideas what would be a suitable license?

**Comment by mbrukman** [comment]
**Disclaimer:** I am not a lawyer, and this is not legal advice. For any legal advice, please contact an attorney.

What I think you're looking for is to have a dual license structure, as you suggested:

* one license for the content, to prohibit reselling it as-is, which CC-BY-NC accomplishes (the non-commercial aspect is literally that)
* another license for the code, so that the code is reusable with someone's original content (the MIT license you're considering would allow this)

FWIW, [JanusGraph][janusgraph] has a dual-license structure and documents explicitly which license applies to which aspects of the repository:

* CC-BY for the docs (this CC license does not restrict commercial usage/distribution)
* Apache 2.0 for the code

Be sure to add license headers to your code (you can use my project [autogen][autogen] to help with this).

Hope this helps and good luck!

[janusgraph]: https://github.com/JanusGraph/janusgraph/blob/master/LICENSE.txt
[autogen]: https://github.com/mbrukman/autogen

**Comment by christophM** [comment]
Thanks a lot for the suggestions. I updated the license
