### ISSUE TITLE
Predictions missing for examples

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#135]
For the examples (bike and cervical), the predictions are missing. I think the example would work better with the model predictions for those instances.

**Comment by TobiasGoerke** [comment]
I do not quite understand what this issue is referring to. Do you suggest to show the model's actual prediction in the plot?

Right now, the plot shows which label is being explained on the y-Axis. This might differ from the model's predicted label.

![grafik](https://user-images.githubusercontent.com/13769461/63263802-d87eaf80-c289-11e9-90b6-35d08c86e603.png)
