### ISSUE TITLE
Feature importance disadvantages

### ISSUE THREAD

**Issue by PhilippPro** [christophM/interpretable-ml-book#69]
I think there could be added some disadvantages in the feature importance chapter. 

There is this paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-8-25

Moreover there is the problem of correlated variables. If two variables are highly correlated, their feature importance could be massively decreased, because one variable can substitute the other variable (for example when we grow a lot of trees). Here is a good blogpost about it, there are for sure some papers about this topic, I guess: https://freakonometrics.hypotheses.org/20545

Btw. you should cite Breiman, 2001, not 2011, as he already died in 2005. ;)

**Comment by christophM** [comment]
Thanks, I updated the date. 
Also I added a point to disadvantages when features are correlated.
But it is a different disadvantage: When features are correlated, then we measure the drop in performance for instances that are very unlikely. 
https://christophm.github.io/interpretable-ml-book/feature-importance.html

I think that the point that you mentioned is not as problematic as some people say. Feature importance is about how important a feature was for the model to make the prediction and at this point I don't care if it was because the feature acted as a proxy for the the correlated feature.
In the blog post example, feature x1 and x2 were correlated, but only feature 1x was relevant for producing the real outcome. Let's say some ml model uses both correlated features (e.g. random forest with some trees using feature x1, some using feature x2) then both features will be important, even though it would be enough to have a model using only feature x1. Since the model relies on both features for the prediction, I think it is correct that the feature importance is decreased for feature x1 and increased for feature x2. It reflects the model behaviour.

The problem is that the underlying model is not a causal model, and it shouldn't be using x2 in the first place.

**Comment by christophM** [comment]
I discussed this a bit with @heidiseibold and now understand a bit more what the problem is. 
In conclusion, I added your point to Disadvantages.

Does that reflect the point you mentioned?

**Comment by PhilippPro** [comment]
Yes. To some other methods this applies as well, so it maybe is not a special problem of the FI. For others there is no influence, e.g. if we simply calculate correlations between the outcome and the variables there is no effect of other variables. 

The sentence at the end can be deleted or changed I think ("The problem is that the underlying model is not a causal model, and it shouldn't be using x2 in the first place.").
